import React, { useState } from "react";
import {
  Box,
  Typography,
  Grid,
  Paper,
  IconButton,
  TextField,
  InputAdornment,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from "@mui/material";
import {
  Search as SearchIcon,
  Settings as SettingsIcon,
  Notifications as NotificationsIcon,
  People as PeopleIcon,
} from "@mui/icons-material";
import { useNavigate } from "react-router-dom";
import Sidebar from "../components/Sidebar";

const Dashboard = () => {
  const navigate = useNavigate();
  const [darkMode, setDarkMode] = useState(false);

  // Sample Data
  const agentLeads = [
    { id: 1, name: "Manasi", today: 0, month: 0, total: 460 },
    { id: 2, name: "Aaliya", today: 0, month: 0, total: 289 },
    { id: 3, name: "Dipak Singh", today: 0, month: 0, total: 36 },
  ];

  const leadSources = [
    { id: 1, source: "IVR", today: 0, month: 0, total: 192 },
    { id: 2, source: "Facebook", today: 0, month: 0, total: 2 },
    { id: 3, source: "Google", today: 0, month: 0, total: 0 },
  ];

  return (
    <Box
      sx={{
        display: "flex",
        bgcolor: darkMode ? "#121212" : "#E3E7F1",
        color: darkMode ? "#fff" : "#000",
        minHeight: "100vh",
        width: "100vw", // Full-screen coverage
      }}
    >
      <Sidebar />

      <Box sx={{ flexGrow: 1, p: 4 }}>
        {/* Header Section */}
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            mb: 4,
            bgcolor: "white",
            p: 2,
            borderRadius: 2,
            boxShadow: 2,
          }}
        >
          <Typography variant="h5" fontWeight="bold">
            Dashboard
          </Typography>

          <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
            <TextField
              size="small"
              placeholder="Search"
              variant="outlined"
              sx={{ bgcolor: "#f8f9fa", borderRadius: 1 }}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <SearchIcon />
                  </InputAdornment>
                ),
              }}
            />

            <IconButton onClick={() => navigate("/settings")}>
              <SettingsIcon />
            </IconButton>

            <IconButton>
              <NotificationsIcon color="primary" />
              <Box
                sx={{
                  position: "absolute",
                  top: "8px",
                  right: "8px",
                  width: "16px",
                  height: "16px",
                  backgroundColor: "red",
                  borderRadius: "50%",
                  color: "white",
                  fontSize: "10px",
                  textAlign: "center",
                  fontWeight: "bold",
                }}
              >
                5
              </Box>
            </IconButton>

            <IconButton onClick={() => navigate("/profile")}>
              <PeopleIcon />
            </IconButton>
          </Box>
        </Box>

        {/* Dashboard Cards */}
        <Grid container spacing={3}>
          {[
            { title: "Total Leads Generated", value: 807, color: "blue" },
            { title: "Missed Follow-ups", value: 15, color: "red" },
            { title: "Total Assigned Leads", value: 431, color: "blue" },
            { title: "Today's Generated Leads", value: 0, color: "green" },
          ].map((card, index) => (
            <Grid item xs={12} sm={6} md={3} key={index}>
              <Paper
                sx={{
                  p: 3,
                  bgcolor: card.color,
                  color: "white",
                  textAlign: "center",
                  borderRadius: 2,
                  boxShadow: 3,
                  minHeight: "100px",
                  display: "flex",
                  flexDirection: "column",
                  justifyContent: "center",
                }}
              >
                <Typography variant="h4" fontWeight="bold">
                  {card.value}
                </Typography>
                <Typography variant="subtitle1">{card.title}</Typography>
              </Paper>
            </Grid>
          ))}
        </Grid>

        {/* Tables Section */}
        <Grid container spacing={3} sx={{ mt: 4 }}>
          {/* Leads Generated by Agents */}
          <Grid item xs={12} md={6}>
            <Paper sx={{ p: 2, borderRadius: 2, boxShadow: 3 }}>
              <Typography
                variant="h6"
                sx={{
                  backgroundColor: "blue",
                  color: "white",
                  p: 1,
                  textAlign: "center",
                  borderRadius: "5px 5px 0 0",
                }}
              >
                Leads Generated by Agents
              </Typography>
              <TableContainer>
                <Table sx={{ minWidth: 300 }}>
                  <TableHead sx={{ bgcolor: "#f0f0f0" }}>
                    <TableRow>
                      <TableCell><strong>Sr.</strong></TableCell>
                      <TableCell><strong>Agent Name</strong></TableCell>
                      <TableCell><strong>Today</strong></TableCell>
                      <TableCell><strong>Current Month</strong></TableCell>
                      <TableCell><strong>All Leads</strong></TableCell>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {agentLeads.map((row) => (
                      <TableRow key={row.id} hover>
                        <TableCell>{row.id}</TableCell>
                        <TableCell>{row.name}</TableCell>
                        <TableCell>{row.today}</TableCell>
                        <TableCell>{row.month}</TableCell>
                        <TableCell>{row.total}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </TableContainer>
            </Paper>
          </Grid>

          {/* Leads Source */}
          <Grid item xs={12} md={6}>
            <Paper sx={{ p: 2, borderRadius: 2, boxShadow: 3 }}>
              <Typography
                variant="h6"
                sx={{
                  backgroundColor: "blue",
                  color: "white",
                  p: 1,
                  textAlign: "center",
                  borderRadius: "5px 5px 0 0",
                }}
              >
                Leads Source
              </Typography>
              <TableContainer>
                <Table sx={{ minWidth: 300 }}>
                  <TableHead sx={{ bgcolor: "#f0f0f0" }}>
                    <TableRow>
                      <TableCell><strong>Sr.</strong></TableCell>
                      <TableCell><strong>Source Name</strong></TableCell>
                      <TableCell><strong>Today</strong></TableCell>
                      <TableCell><strong>Current Month</strong></TableCell>
                      <TableCell><strong>All Leads</strong></TableCell>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {leadSources.map((row) => (
                      <TableRow key={row.id} hover>
                        <TableCell>{row.id}</TableCell>
                        <TableCell>{row.source}</TableCell>
                        <TableCell>{row.today}</TableCell>
                        <TableCell>{row.month}</TableCell>
                        <TableCell>{row.total}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </TableContainer>
            </Paper>
          </Grid>
        </Grid>
      </Box>
    </Box>
  );
};

export default Dashboard;
